// Command gen-stations fetches the TRA station catalog from TDX's /Station
// endpoint and regenerates internal/domain/stations_data.go.
//
// §6.2 of the spec is explicit that /Station is a build-time-only lookup —
// the running program must never call it. This tool is that build-time
// lookup: run it once (and again whenever TRA adds or renames a station),
// commit the regenerated file, and the running program never touches the
// network for station data at all.
//
//	go run ./cmd/gen-stations
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"text/template"
	"time"

	_ "time/tzdata"

	"github.com/nekogravitycat/tra-commute-bot/internal/adapter/tdx"
	"github.com/nekogravitycat/tra-commute-bot/internal/config"
	"github.com/nekogravitycat/tra-commute-bot/internal/domain"
)

const outPath = "internal/domain/stations_data.go"

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	if err := config.LoadDotEnv(".env"); err != nil {
		log.Printf("warning: could not read .env: %v", err)
	}
	creds, err := config.LoadCredentials()
	if err != nil {
		return fmt.Errorf("load TDX credentials: %w", err)
	}

	loc, err := time.LoadLocation("Asia/Taipei")
	if err != nil {
		return fmt.Errorf("load timezone: %w", err)
	}

	client := tdx.New(tdx.Credentials{
		ClientID:     creds.TDXClientID,
		ClientSecret: creds.TDXClientSecret,
	}, loc, tdx.Options{Interval: 1500 * time.Millisecond, Timeout: 15 * time.Second})

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := client.Authenticate(ctx); err != nil {
		return fmt.Errorf("authenticate: %w", err)
	}
	stations, err := client.Stations(ctx)
	if err != nil {
		return fmt.Errorf("fetch stations: %w", err)
	}
	if len(stations) == 0 {
		return fmt.Errorf("TDX returned zero stations — refusing to overwrite %s with an empty catalog", outPath)
	}

	sort.Slice(stations, func(i, j int) bool {
		ni, erri := strconv.Atoi(stations[i].ID)
		nj, errj := strconv.Atoi(stations[j].ID)
		if erri == nil && errj == nil {
			return ni < nj
		}
		return stations[i].ID < stations[j].ID
	})

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create %s: %w", outPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, struct {
		GeneratedAt string
		Count       int
		Stations    []domain.Station
	}{
		GeneratedAt: time.Now().In(loc).Format("2006-01-02"),
		Count:       len(stations),
		Stations:    stations,
	}); err != nil {
		return fmt.Errorf("render %s: %w", outPath, err)
	}

	fmt.Printf("wrote %d stations to %s\n", len(stations), outPath)
	return nil
}

var tmpl = template.Must(template.New("stations").Parse(`// Code generated by cmd/gen-stations from TDX /Station on {{.GeneratedAt}}. DO NOT EDIT.
//
// Regenerate with: go run ./cmd/gen-stations
// ({{.Count}} stations)

package domain

// AllStations is the full TRA station catalog, embedded at build time so
// /setup's station matcher (MatchStations) needs no network call in
// production — see §6.2's note that /Station is a build-time-only lookup.
var AllStations = []Station{
{{- range .Stations}}
	{ID: {{printf "%q" .ID}}, NameZh: {{printf "%q" .NameZh}}, NameEn: {{printf "%q" .NameEn}}},
{{- end}}
}
`))
